name: Compressed Size Compare

on:
  pull_request:
    paths:
      - src/**/*.ts
      - tools/*.ts
      - gulpfile.ts
      - tsconfig.json
      - package.json
      - yarn.lock
    branches:
      - dev
      - main

concurrency:
  group: compressed-size-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Compressed size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: ./dist/**/*.js
          compression: none
          build-script: build:all
