name: lint-code

on:
  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
      - name: Lint commit
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
          failOnWarnings: true
